# [사이트 기본 정보]
url: "https://seunghee-data.github.io"
baseurl: ""
title: "StudioSon"
locale: "ko-KR"          # 필수: 검색, 공유 등 모든 메뉴를 한글로 변환함
timezone: Asia/Seoul

# [테마 및 플러그인]
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# [기능 활성화]
navigation: main         # 중요: _data/navigation.yml 메뉴를 상단에 띄움

# [디자인 설정]
minimal_mistakes_skin: "dark" # 스킨 (default, air, aqua, contrast 등 선택 가능)

# [저자(대표님) 프로필 설정] - 왼쪽 사이드바에 표시됨
author:
  name: "손승희 | Data Lab"
  bio: "영상 10년, 이제 데이터로 미래를 봅니다"
  location: "Incheon, South Korea"
  avatar: "/assets/images/profile.png"
collections:
  pages:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
